export function translateIngredient(ingredient: string): string {
    const translations: Record<string, string> = {
        tomate: "tomato",
        tomaten: "tomato",
        kartoffel: "potato",
        kartoffeln: "potato",
        reis: "rice",
        ei: "egg",
        eier: "egg",
        käse: "cheese",
        zwiebel: "onion",
        zwiebeln: "onion",
        paprika: "pepper",
        gurke: "cucumber",
        salat: "lettuce",
        hähnchen: "chicken",
        huhn: "chicken",
        nudeln: "pasta",
        pasta: "pasta",
        milch: "milk",
        butter: "butter",
        brot: "bread",
        pilze: "mushroom",
        champignons: "mushroom",
        karotte: "carrot",
        karotten: "carrot",
        zucchini: "zucchini",
        mais: "corn",
        thunfisch: "tuna",
        lachs: "salmon",
        rindfleisch: "beef",
        faschiertes: "beef",
        bohnen: "beans",
        erbsen: "peas",
        spinat: "spinach",
    };

    return translations[ingredient.toLowerCase()] || ingredient.toLowerCase();
}